# Nav
social:
  Github: https://gitee.com/fybug/Design
  RSS: /atom.xml

# Background image, color
background: 'url(http://osly086qe.bkt.clouddn.com/button-bg.png) #f3f3f3'

# Favicon
favicon: /designgallery/favicon.png

# Widgets, enable at least one
widgets:
  category: enabled
  archive: enabled
  tag: enabled

# Set the first image in post to cover
auto_cover: true
